#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -d "/app/diskover-tmp" ]; then
    echo "New container detected. Setting up app folder and fixing permissions."
    mv /app/diskover-tmp /app/diskover
fi

if [ -d "/app/diskover-web-tmp" ]; then
    mv /app/diskover-web-tmp /app/www
fi

lsiown -R abc:abc /app
