#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# setup web
mkdir -p \
    /config/diskover-web.conf.d

# touch db
if [[ ! -e "/config/diskoverdb.sqlite3" ]]; then
    touch /config/diskoverdb.sqlite3
fi

lsiown -R abc:abc /config
