#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# setup web
mkdir -p \
    /config/diskover-web.conf.d

# touch db
if [[ ! -e "/config/diskoverdb.sqlite3" ]]; then
    touch /config/diskoverdb.sqlite3
fi
ln -sf /config/diskoverdb.sqlite3 /app/diskover-web/diskoverdb.sqlite3

ln -sf /config/diskover-web.conf.d/Constants.php /app/diskover-web/src/diskover/Constants.php

lsiown -R abc:abc /config
