#!/usr/bin/with-contenv bash

# need to safely handle exiting the existing worker bots and
# redis queue when container restarts or stops

. /config/.env

# define array for input values
declare -A DISKOVER_ARRAY
DISKOVER_ARRAY[REDIS_HOST]=${REDIS_HOST:-redis}
DISKOVER_ARRAY[REDIS_PORT]=${REDIS_PORT:-6379}

DISKOVER_ARRAY[DISKOVER_OPTS]="${DISKOVER_ARRAY[DISKOVER_OPTS]} -i ${DISKOVER_ARRAY[INDEX_NAME]}"

_term() {
	#/bin/bash /app/cleanup.sh
	# Redis Cleanup
	# killing existing workers before starting new ones
	echo "killing existing workers..."
	if [ -f "/tmp/diskover_bot_pids" ]; then
	    /bin/bash /app/diskover/diskover-bot-launcher.sh -k > /dev/null 2>&1
	    sleep 3
	fi
	# empty existing redis queue
	echo "emptying current redis queues..."
	rq empty -u redis://"${DISKOVER_ARRAY[REDIS_HOST]}":"${DISKOVER_ARRAY[REDIS_PORT]}" diskover_crawl diskover diskover_calcdir failed
	sleep 3
	# kill dangling workers
	echo "killing dangling workers..."
	/bin/bash /app/diskover/diskover-bot-launcher.sh -k > /dev/null 2>&1
	sleep 3
}

trap _term SIGTERM

declare -A REDIS_CONF
REDIS_CONF[REDIS_HOST]=${REDIS_HOST:-redis}
REDIS_CONF[REDIS_PORT]=${REDIS_PORT:-6379}

exec \
	s6-setuidgid abc /usr/bin/rq-dashboard -H ${REDIS_CONF[REDIS_HOST]} -P ${REDIS_CONF[REDIS_PORT]}