#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make crontab config folder
mkdir -p \
    /config/crontabs

# copy crontabs if needed
if [[ ! -f /config/crontabs/abc ]]; then
    cp /etc/crontabs/abc /config/crontabs/
fi

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/
