#!/usr/bin/with-contenv bash

# set default values for variables
REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
ES_HOST=${ES_HOST:-elasticsearch}
ES_PORT=${ES_PORT:-9200}
ES_USER=${ES_USER:-elastic}
ES_PASS=${ES_PASS:-changeme}

# persist env variables
if [ ! -f "/config/.env" ]; then
	echo "export REDIS_HOST="$REDIS_HOST"
export REDIS_PORT="$REDIS_PORT"
export ES_HOST="$ES_HOST"
export ES_PORT="$ES_PORT"
export ES_USER="$ES_USER"
export ES_PASS="$ES_PASS"" > /config/.env
fi

if [ ! -f "/etc/profile.d/diskover.sh" ]; then
	ln -s /config/.env /etc/profile.d/diskover.sh
fi

# create folders
mkdir -p \
	/config/{log/diskover,crontabs}

if [ ! -f "/config/diskover.cfg" ]; then
	mv /defaults/diskover.cfg /config/diskover.cfg
	sed -i 's|{{REDIS_HOST}}|'$REDIS_HOST'|g' /config/diskover.cfg
	sed -i 's|{{REDIS_PORT}}|'$REDIS_PORT'|g' /config/diskover.cfg
	sed -i 's|{{ES_HOST}}|'$ES_HOST'|g' /config/diskover.cfg
	sed -i 's|{{ES_PORT}}|'$ES_PORT'|g' /config/diskover.cfg
	sed -i 's|{{ES_USER}}|'$ES_USER'|g' /config/diskover.cfg
	sed -i 's|{{ES_PASS}}|'$ES_PASS'|g' /config/diskover.cfg
fi

if [ ! -f "/app/diskover/diskover.cfg" ]; then
	ln -s /config/diskover.cfg /app/diskover/diskover.cfg
fi

# copy crontab and proxy defaults if needed
[[ ! -f /config/crontabs/abc ]] && \
	cp /etc/crontabs/abc /config/crontabs/

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/

# permissions
chmod +x \
	/app/dispatcher.sh
chown -R abc:abc \
	/app/diskover \
	/config

# sleep to allow time for elasticsearch to start
cd /app/diskover || exit

# run initial retrieval
if [ $RUN_ON_START ]; then
	sleep 10
	echo "Initial run of dispatcher in progress"
	exec \
		s6-setuidgid abc /app/dispatcher.sh >> /config/log/diskover/dispatcher.log 2>&1 &
fi
