#!/usr/bin/with-contenv bash

# set default values for variables
REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
ES_HOST=${ES_HOST:-elasticsearch}
ES_PORT=${ES_PORT:-9200}
ES_USER=${ES_USER:-elastic}
ES_PASS=${ES_PASS:-changeme}

# create folders
mkdir -p \
	/config/log/diskover

if [ ! -f "/config/diskover.cfg" ]; then
	mv /defaults/diskover.cfg /config/diskover.cfg
	sed -i 's|{{REDIS_HOST}}|'$REDIS_HOST'|g' /config/diskover.cfg
	sed -i 's|{{REDIS_PORT}}|'$REDIS_PORT'|g' /config/diskover.cfg
	sed -i 's|{{ES_HOST}}|'$ES_HOST'|g' /config/diskover.cfg
	sed -i 's|{{ES_PORT}}|'$ES_PORT'|g' /config/diskover.cfg
	sed -i 's|{{ES_USER}}|'$ES_USER'|g' /config/diskover.cfg
	sed -i 's|{{ES_PASS}}|'$ES_PASS'|g' /config/diskover.cfg
fi

if [ ! -f "/app/diskover/diskover.cfg" ]; then
	ln -s /config/diskover.cfg /app/diskover/diskover.cfg
fi

if [ ! -f "/config/crontab" ]; then
	cp /defaults/crontab /config/crontab
fi

if [ ! -f "/etc/crontabs/abc" ]; then
	if [ $USE_CRON ]; then
		ln -s /config/crontab /etc/crontabs/abc
	fi
fi

# permissions
chmod +x \
	/app/dispatcher.sh
chown -R abc:abc \
	/app/diskover \
	/config

# sleep to allow time for elasticsearch to start
sleep 10
cd /app/diskover || exit

# run initial retrieval
echo "Initial run of dispatcher in progress"
exec \
	s6-setuidgid abc /app/dispatcher.sh >> /config/log/diskover/dispatcher.log 2>&1 &
