#!/usr/bin/with-contenv bash

if [ -f /config/diskover.cfg ]; then
    echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*     We have detected that you have an existing     *
*                                                    *
*   diskover v1 config file. Version 1 is now EOL.   *
*                                                    *
*    If you would like to upgrade, please create a   *
*                                                    *
*   new /config directory. If you want to continue   *
*                                                    *
*  using version 1, specify the tag v1.5.0.13-ls33.  *
*                                                    *
*                More information at                 *
*                                                    *
* https://github.com/diskoverdata/diskover-community *
*                                                    *
*                                                    *
******************************************************
******************************************************'
    while true
    do
        sleep 3600
    done
fi
