#!/usr/bin/with-contenv bash

# set default values for variables
declare -A WEB_CONF
WEB_CONF[ES_HOST]=${ES_HOST:-elasticsearch}
WEB_CONF[ES_PORT]=${ES_PORT:-9200}
WEB_CONF[ES_USER]=${ES_USER:-}
WEB_CONF[ES_PASS]=${ES_PASS:-}

mkdir -p \
    /config/diskover-web.conf.d

# copy over sample config files
cd /app/diskover-web/public
for file in *.sample; do
    dest=${file%.sample}

    [[ ! -e "/config/diskover-web.conf.d/$dest" ]] && \
        cp /app/diskover-web/public/$file /config/diskover-web.conf.d/$dest

    ln -sf /config/diskover-web.conf.d/$dest /app/diskover-web/public/$dest
done

# copy and set variables in Constants.php
if [[ ! -e "/config/diskover-web.conf.d/Constants.php" ]]; then
    cp /app/diskover-web/src/diskover/Constants.php.sample /config/diskover-web.conf.d/Constants.php

    sed -i "s|const TIMEZONE = 'America/Vancouver';|const TIMEZONE = '${TZ}';|g" /config/diskover-web.conf.d/Constants.php
    sed -i "s|const ES_HOST = 'localhost';|const ES_HOST = '${WEB_CONF[ES_HOST]}';|g" /config/diskover-web.conf.d/Constants.php
    sed -i "s|const ES_PORT = 9200;|const ES_PORT = ${WEB_CONF[ES_PORT]};|g" /config/diskover-web.conf.d/Constants.php
    sed -i "s|const ES_USER = '';|const ES_USER = '${WEB_CONF[ES_USER]}';|g" /config/diskover-web.conf.d/Constants.php
    sed -i "s|const ES_PASS = '';|const ES_PASS = '${WEB_CONF[ES_PASS]}';|g" /config/diskover-web.conf.d/Constants.php
fi

ln -sf /config/diskover-web.conf.d/Constants.php /app/diskover-web/src/diskover/Constants.php

chown -R abc:abc /config
